server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/healthCare?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: 1234
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 3
      connection-timeout: 5000
      minimum-idle: 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    key: f1911415b21fdb5fa9b8996b670b2c5b710f1e8e617ed2892c3df07e6d9120c594e941660fe879f6882c2f83c71cb27dfd25783177f08852cc72b06c7bf8c862
  token:
    access:
      expiration_time: 600000
    refresh:
      expiration_time: 1800000